#언어
language: generic

#수도 권한주기
sudo: required

#도커환경 만들어주기
services:
  - docker

#도커파일을 이용하여 이미지를 생성
#  -t alstkd1q1q/react-test-app 해당 이름으로 
# 테스트파일 수행하기 위해 -f ./frontend/Dockerfile.dev ./frontend
before_install:
  - docker build -t alstkd1q1q/react-test-app -f ./frontend/Dockerfile.dev ./frontend

#이미지를 컨테이너로 만든다. CI=true , 이미지이름 명령어
script:
  - docker run -e CI=true alstkd1q1q/react-test-app npm run test


#테스트 성공후
#이미 도커파일이 있기때문에 도커 해당 경로만 넣어주면된다. 
#각각의 이미지를 빌드
after_success:
  - docker build -t alstkd1q1q/docker-frontend ./forntend
  - docker build -t alstkd1q1q/docker-backend ./backend
  - docker build -t alstkd1q1q/nginx ./nginx

#도커허브에 로그인
-echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

#도커허브에 빌드된 이미지를 업로드
- docker push alstkd1q1q/docker-frontend
- docker push alstkd1q1q/docker-backend
- docker push alstkd1q1q/nginx


#배포
deploy:
  provider : elasticbeanstalk #제공자 우리는 aws에 eb 사용 
  region : :ap-northeast-2" #서울서버 주소
  app: "docker-fullstack-app"  #에플리케이션이름
  env: "DockerFullstackApp-env" #환경이름 
  bucket_name: elasticbeanstal-ap-northeast-2-972153559337  # s3의 버켓이름 . eb에 바로 배포가 아니라 먼저 s3 스토리지에 파일을 저장하고 배포
  bucket_path : "docker-fullstack-app" #app이름과 같다.
  on : #어떤 브랜치에 push 되었을때 deploy 되는지 
    branch: master 
  #aws 접근 키 < travis 해당 계정에 환경변수로 설정을 해두었다.
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key : $AWS_SECRET_ACCESS_KEY